### ISSUE TITLE
Creepies you own will aggro on you when you punch them

### ISSUE THREAD

**Issue by thelegitdolt** [MoonflowerTeam/tolerable-creepers#9]
### What version are you seeing the problem on?

1.16.5

### Describe the issue

```markdown
1. use a spore cloud to summon creepies
2. punch one
3. Notice that it aggroes on you.

They will aggro on you even if you are in creative mode, which is not supposed to happen.

However, creepers summoned by dispensers or creeper explosions will not aggro on you if punched in creative mode.
```

### latest.log

```shell
not necessary
```

**Comment by Ocelot5836** [comment]
I can't seem to be able to replicate this issue on 1.18 or 1.19. The creepies don't aggro when I punch them in a creative test world after spawned from creeper spores.

**Comment by thelegitdolt** [comment]
this issue is from  half a year ago, using an instance with just pollen + TC. Though if you are unable to reproduce, maybe the issue fixed itself through all the ports somehow?

**Comment by Ocelot5836** [comment]
I'll go ahead and mark it as fixed then
